version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Bahia
    open-pull-requests-limit: 5
    groups:
      production-minor-patch:
        applies-to: version-updates
        dependency-type: production
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      development-minor-patch:
        applies-to: version-updates
        dependency-type: development
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: America/Bahia
    open-pull-requests-limit: 5
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - '*'
